//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCC.PROMOTION.MerchAppManager {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConnectionModel", Namespace="http://schemas.datacontract.org/2004/07/KCC.Merch.AppManager.Core.Model")]
    [System.SerializableAttribute()]
    public partial class ConnectionModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AutoEmailModel", Namespace="http://schemas.datacontract.org/2004/07/KCC.Merch.AppManager.Core.Model")]
    [System.SerializableAttribute()]
    public partial class AutoEmailModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ApplicationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AutoEmailLogIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PinCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TranNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ApplicationId {
            get {
                return this.ApplicationIdField;
            }
            set {
                if ((this.ApplicationIdField.Equals(value) != true)) {
                    this.ApplicationIdField = value;
                    this.RaisePropertyChanged("ApplicationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AutoEmailLogId {
            get {
                return this.AutoEmailLogIdField;
            }
            set {
                if ((this.AutoEmailLogIdField.Equals(value) != true)) {
                    this.AutoEmailLogIdField = value;
                    this.RaisePropertyChanged("AutoEmailLogId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((this.CreatedByField.Equals(value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageContent {
            get {
                return this.MessageContentField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageContentField, value) != true)) {
                    this.MessageContentField = value;
                    this.RaisePropertyChanged("MessageContent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PinCode {
            get {
                return this.PinCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PinCodeField, value) != true)) {
                    this.PinCodeField = value;
                    this.RaisePropertyChanged("PinCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestedBy {
            get {
                return this.RequestedByField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestedByField, value) != true)) {
                    this.RequestedByField = value;
                    this.RaisePropertyChanged("RequestedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TranNo {
            get {
                return this.TranNoField;
            }
            set {
                if ((this.TranNoField.Equals(value) != true)) {
                    this.TranNoField = value;
                    this.RaisePropertyChanged("TranNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OutTownModel", Namespace="http://schemas.datacontract.org/2004/07/KCC.Merch.AppManager.Core.Model")]
    [System.SerializableAttribute()]
    public partial class OutTownModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ApplicationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InitialAppNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OutTownIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ApplicationId {
            get {
                return this.ApplicationIdField;
            }
            set {
                if ((this.ApplicationIdField.Equals(value) != true)) {
                    this.ApplicationIdField = value;
                    this.RaisePropertyChanged("ApplicationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((this.CreatedByField.Equals(value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InitialAppName {
            get {
                return this.InitialAppNameField;
            }
            set {
                if ((object.ReferenceEquals(this.InitialAppNameField, value) != true)) {
                    this.InitialAppNameField = value;
                    this.RaisePropertyChanged("InitialAppName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OutTownId {
            get {
                return this.OutTownIdField;
            }
            set {
                if ((this.OutTownIdField.Equals(value) != true)) {
                    this.OutTownIdField = value;
                    this.RaisePropertyChanged("OutTownId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserModel", Namespace="http://schemas.datacontract.org/2004/07/KCC.Merch.AppManager.Core.Model")]
    [System.SerializableAttribute()]
    public partial class UserModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((this.CreatedByField.Equals(value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MerchAppManager.IAutoEmailLogs")]
    public interface IAutoEmailLogs {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoEmailLogs/GetAllAppTranRequest", ReplyAction="http://tempuri.org/IAutoEmailLogs/GetAllAppTranRequestResponse")]
        string GetAllAppTranRequest(KCC.PROMOTION.MerchAppManager.ConnectionModel credential);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoEmailLogs/GetAppTranRequest", ReplyAction="http://tempuri.org/IAutoEmailLogs/GetAppTranRequestResponse")]
        string GetAppTranRequest(KCC.PROMOTION.MerchAppManager.ConnectionModel credential, int appId, int tranNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoEmailLogs/ConfirmAppTranRequest", ReplyAction="http://tempuri.org/IAutoEmailLogs/ConfirmAppTranRequestResponse")]
        string ConfirmAppTranRequest(KCC.PROMOTION.MerchAppManager.ConnectionModel credential, int appId, int tranNo, string pinCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoEmailLogs/AddAutoEmailLogs", ReplyAction="http://tempuri.org/IAutoEmailLogs/AddAutoEmailLogsResponse")]
        string AddAutoEmailLogs(KCC.PROMOTION.MerchAppManager.ConnectionModel credential, KCC.PROMOTION.MerchAppManager.AutoEmailModel autoEmailModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoEmailLogs/ModifyAutoEmailLogStatus", ReplyAction="http://tempuri.org/IAutoEmailLogs/ModifyAutoEmailLogStatusResponse")]
        string ModifyAutoEmailLogStatus(KCC.PROMOTION.MerchAppManager.ConnectionModel credential, KCC.PROMOTION.MerchAppManager.AutoEmailModel autoEmailModel);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAutoEmailLogsChannel : KCC.PROMOTION.MerchAppManager.IAutoEmailLogs, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AutoEmailLogsClient : System.ServiceModel.ClientBase<KCC.PROMOTION.MerchAppManager.IAutoEmailLogs>, KCC.PROMOTION.MerchAppManager.IAutoEmailLogs {
        
        public AutoEmailLogsClient() {
        }
        
        public AutoEmailLogsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AutoEmailLogsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutoEmailLogsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutoEmailLogsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetAllAppTranRequest(KCC.PROMOTION.MerchAppManager.ConnectionModel credential) {
            return base.Channel.GetAllAppTranRequest(credential);
        }
        
        public string GetAppTranRequest(KCC.PROMOTION.MerchAppManager.ConnectionModel credential, int appId, int tranNo) {
            return base.Channel.GetAppTranRequest(credential, appId, tranNo);
        }
        
        public string ConfirmAppTranRequest(KCC.PROMOTION.MerchAppManager.ConnectionModel credential, int appId, int tranNo, string pinCode) {
            return base.Channel.ConfirmAppTranRequest(credential, appId, tranNo, pinCode);
        }
        
        public string AddAutoEmailLogs(KCC.PROMOTION.MerchAppManager.ConnectionModel credential, KCC.PROMOTION.MerchAppManager.AutoEmailModel autoEmailModel) {
            return base.Channel.AddAutoEmailLogs(credential, autoEmailModel);
        }
        
        public string ModifyAutoEmailLogStatus(KCC.PROMOTION.MerchAppManager.ConnectionModel credential, KCC.PROMOTION.MerchAppManager.AutoEmailModel autoEmailModel) {
            return base.Channel.ModifyAutoEmailLogStatus(credential, autoEmailModel);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MerchAppManager.IOutTownMode")]
    public interface IOutTownMode {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOutTownMode/GetAllOutTownModeApp", ReplyAction="http://tempuri.org/IOutTownMode/GetAllOutTownModeAppResponse")]
        string GetAllOutTownModeApp(KCC.PROMOTION.MerchAppManager.ConnectionModel credential);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOutTownMode/GetOutTownModeApp", ReplyAction="http://tempuri.org/IOutTownMode/GetOutTownModeAppResponse")]
        string GetOutTownModeApp(KCC.PROMOTION.MerchAppManager.ConnectionModel credential, int appId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOutTownMode/AddOutTownMode", ReplyAction="http://tempuri.org/IOutTownMode/AddOutTownModeResponse")]
        string AddOutTownMode(KCC.PROMOTION.MerchAppManager.ConnectionModel credential, KCC.PROMOTION.MerchAppManager.OutTownModel outTownModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOutTownMode/ModifyOutTownMode", ReplyAction="http://tempuri.org/IOutTownMode/ModifyOutTownModeResponse")]
        string ModifyOutTownMode(KCC.PROMOTION.MerchAppManager.ConnectionModel credential, KCC.PROMOTION.MerchAppManager.OutTownModel outTownModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOutTownMode/GetAllApplication", ReplyAction="http://tempuri.org/IOutTownMode/GetAllApplicationResponse")]
        string GetAllApplication(KCC.PROMOTION.MerchAppManager.ConnectionModel credential);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOutTownMode/GetApplication", ReplyAction="http://tempuri.org/IOutTownMode/GetApplicationResponse")]
        string GetApplication(KCC.PROMOTION.MerchAppManager.ConnectionModel credential, int appId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOutTownModeChannel : KCC.PROMOTION.MerchAppManager.IOutTownMode, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OutTownModeClient : System.ServiceModel.ClientBase<KCC.PROMOTION.MerchAppManager.IOutTownMode>, KCC.PROMOTION.MerchAppManager.IOutTownMode {
        
        public OutTownModeClient() {
        }
        
        public OutTownModeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OutTownModeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OutTownModeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OutTownModeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetAllOutTownModeApp(KCC.PROMOTION.MerchAppManager.ConnectionModel credential) {
            return base.Channel.GetAllOutTownModeApp(credential);
        }
        
        public string GetOutTownModeApp(KCC.PROMOTION.MerchAppManager.ConnectionModel credential, int appId) {
            return base.Channel.GetOutTownModeApp(credential, appId);
        }
        
        public string AddOutTownMode(KCC.PROMOTION.MerchAppManager.ConnectionModel credential, KCC.PROMOTION.MerchAppManager.OutTownModel outTownModel) {
            return base.Channel.AddOutTownMode(credential, outTownModel);
        }
        
        public string ModifyOutTownMode(KCC.PROMOTION.MerchAppManager.ConnectionModel credential, KCC.PROMOTION.MerchAppManager.OutTownModel outTownModel) {
            return base.Channel.ModifyOutTownMode(credential, outTownModel);
        }
        
        public string GetAllApplication(KCC.PROMOTION.MerchAppManager.ConnectionModel credential) {
            return base.Channel.GetAllApplication(credential);
        }
        
        public string GetApplication(KCC.PROMOTION.MerchAppManager.ConnectionModel credential, int appId) {
            return base.Channel.GetApplication(credential, appId);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MerchAppManager.IUser")]
    public interface IUser {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/GetUserAccess", ReplyAction="http://tempuri.org/IUser/GetUserAccessResponse")]
        string GetUserAccess(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/GetAllUsers", ReplyAction="http://tempuri.org/IUser/GetAllUsersResponse")]
        string GetAllUsers(KCC.PROMOTION.MerchAppManager.ConnectionModel credential);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/GetAllActiveUsers", ReplyAction="http://tempuri.org/IUser/GetAllActiveUsersResponse")]
        string GetAllActiveUsers(KCC.PROMOTION.MerchAppManager.ConnectionModel credential);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/AddUser", ReplyAction="http://tempuri.org/IUser/AddUserResponse")]
        string AddUser(KCC.PROMOTION.MerchAppManager.ConnectionModel credential, KCC.PROMOTION.MerchAppManager.UserModel userModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/ModifyUser", ReplyAction="http://tempuri.org/IUser/ModifyUserResponse")]
        string ModifyUser(KCC.PROMOTION.MerchAppManager.ConnectionModel credential, KCC.PROMOTION.MerchAppManager.UserModel userModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/GetDatabaseDate", ReplyAction="http://tempuri.org/IUser/GetDatabaseDateResponse")]
        string GetDatabaseDate(KCC.PROMOTION.MerchAppManager.ConnectionModel credential);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserChannel : KCC.PROMOTION.MerchAppManager.IUser, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserClient : System.ServiceModel.ClientBase<KCC.PROMOTION.MerchAppManager.IUser>, KCC.PROMOTION.MerchAppManager.IUser {
        
        public UserClient() {
        }
        
        public UserClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetUserAccess(string username, string password) {
            return base.Channel.GetUserAccess(username, password);
        }
        
        public string GetAllUsers(KCC.PROMOTION.MerchAppManager.ConnectionModel credential) {
            return base.Channel.GetAllUsers(credential);
        }
        
        public string GetAllActiveUsers(KCC.PROMOTION.MerchAppManager.ConnectionModel credential) {
            return base.Channel.GetAllActiveUsers(credential);
        }
        
        public string AddUser(KCC.PROMOTION.MerchAppManager.ConnectionModel credential, KCC.PROMOTION.MerchAppManager.UserModel userModel) {
            return base.Channel.AddUser(credential, userModel);
        }
        
        public string ModifyUser(KCC.PROMOTION.MerchAppManager.ConnectionModel credential, KCC.PROMOTION.MerchAppManager.UserModel userModel) {
            return base.Channel.ModifyUser(credential, userModel);
        }
        
        public string GetDatabaseDate(KCC.PROMOTION.MerchAppManager.ConnectionModel credential) {
            return base.Channel.GetDatabaseDate(credential);
        }
    }
}
